### ISSUE TITLE
Notable figures section?

### ISSUE THREAD

**Issue by alexcg1** [folkswhocode/awesome-diversity#33]
Just today I was thinking about creating an awesome list of the diverse folks involved in the history of our industry (eg Turing, Lovelace, Hopper, etc). Aim would be to show everyone that computing is for EVERYONE, not just the stereotypes people initially expect.

Since you've already got this list up, would it make more sense for me to contribute it to yours? I'd rather contribute to something bigger rather than just start my own thing.

**Comment by tasugo** [comment]
Hi @alexcg1, thanks for taking the time to check our humble list. I think it would make perfect sense to add a section with notable figures.

We had some discussion in the past whether we should include present day activists, because sometimes being public leads to harassment, so that could be up for debate...

But that's not the case with historic figures like you're proposing, and I think it would be a great add.

I'm looking forward to reviewing that PR! :heart:

**Comment by marinavega** [comment]
Hey @alexcg1, thank you so much for your time and contribution. 

A list of historic figures sounds great to me :)

**Comment by dreamingechoes** [comment]
Same here, it would be awesome, thank you @alexcg1! :hugs:

**Comment by alexcg1** [comment]
Great, I'll put something together and make a PR!

**Comment by alexcg1** [comment]
I just tried making a commit but seems I don't have access permissions:

Permission to folkswhocode/awesome-diversity.git denied to alexcg1.

**Comment by dreamingechoes** [comment]
Hi @alexcg1!

the original repository only has permissions for users of the organization. You must follow the usual steps, you know:

```
1. Fork the repository
2. Create your feature branch (`git checkout -b my-new-feature`)
3. Commit your changes (`git commit -am 'Added some feature'`)
4. Push to the branch (`git push origin my-new-feature`)
5. Create new Pull Request in the original repository
```
If you already are making the changes this way, please let me know to check if something is not working properly.

Greetings! :smile:

**Comment by alexcg1** [comment]
Hi @dreamingechoes!

![screenshot from 2018-05-02 11-42-38](https://user-images.githubusercontent.com/4182659/39505651-f7715d22-4dfd-11e8-8f7f-041fd9a0d7d9.png)
Followed instructions as above. Still having the same issue when I get to step 4. Tried with both SSH and https auth :(

**Comment by dreamingechoes** [comment]
Hi @alexcg1!

Uhmmm... is the remote `origin` pointing directly to `git@github.com:folkswhocode/awesome-diversity.git`, or it's pointing to the `URL` of your own repository in your Github account? Because if you try to push any commit or new branch to `git@github.com:folkswhocode/awesome-diversity.git`, it will not work since the only users that have permissions in that repository are the ones of the `folkswhocode`'s organization, nobody outside the organization can push anything directly to the repository.

Can you check the `URL` of your remote and confirm that is not pointing to `git@github.com:folkswhocode/awesome-diversity.git`?

Thank you! :hugs:

**Comment by alexcg1** [comment]
OK, think it's sorted now! I've made a PR
